import { TimelineEvent, LabModule, ViralClaim, ArtifactHotspot, STURPPaper } from './types';

export const APP_VERSION = '1.1.0';

export const EVENTS: TimelineEvent[] = [
  {
    id: 'evt_33',
    year: 33,
    displayDate: '33 AD',
    title: 'The Crucifixion & Burial',
    description: 'The narrative origin. The Gospels describe linen cloths left in the tomb.',
    category: 'THEOLOGY',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Links to 2022 WAXS study dating linen cellulose to this era (Siege of Masada comparison).',
    url: 'https://www.mdpi.com/2079-4991/12/2/222',
  },
  {
    id: 'evt_544',
    year: 544,
    displayDate: '544 AD',
    title: 'Image of Edessa Discovery',
    description: 'A cloth "not made by hands" is found in Edessa walls.',
    category: 'HISTORY',
    consensus: 'NEUTRAL',
    details: 'Supports the "Tetradiplon" theory: the Shroud was folded four times to show only the face.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_550',
    year: 550,
    displayDate: '550 AD',
    title: 'Christ Pantocrator (Sinai)',
    description: 'The oldest surviving icon of Christ (St. Catherine\'s Monastery) exhibits distinct facial asymmetry identical to the Shroud (swollen cheek, displaced nose).',
    category: 'HISTORY',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Suggests the artist used the Shroud as a model 700 years before the radiocarbon date.',
    url: 'https://www.shroud.com/pdfs/vignon.pdf',
  },
  {
    id: 'evt_692',
    year: 692,
    displayDate: '692 AD',
    title: 'Justinian II Coinage',
    description: 'Gold solidus coins minted by Justinian II depict a "Face of Christ" that perfectly overlays with the Shroud (Vignon markings).',
    category: 'HISTORY',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Suggests the Shroud was the visual model for Christ by the 7th century, contradicting the 1260 radiocarbon date.',
    url: 'https://www.shroud.com/pdfs/vignon.pdf',
  },
  {
    id: 'evt_1192',
    year: 1192,
    displayDate: '1192 AD',
    title: 'The Pray Codex',
    description: 'Hungarian manuscript depicts Jesus with thumbs hidden, herringbone weave, and specific L-shaped burn holes matching the Shroud.',
    category: 'HISTORY',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Predates the C14 dating by centuries, suggesting the Shroud existed before 1260.',
    url: 'https://www.shroud.com/pdfs/berglund.pdf',
  },
  {
    id: 'evt_1203',
    year: 1203,
    displayDate: '1203 AD',
    title: 'Robert de Clari Witness',
    description: 'Crusader knight Robert de Clari reports seeing a cloth in Constantinople "which raised itself up upright" every Friday, showing the figure of Christ.',
    category: 'HISTORY',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Describes the "Sydoine" at the Church of St. Mary of Blachernae, linking the Shroud to the East.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1204',
    year: 1204,
    displayDate: '1204 AD',
    title: 'The Missing Years',
    description: 'Crusaders sack Constantinople. The cloth disappears from history for 150 years.',
    category: 'HISTORY',
    consensus: 'NEUTRAL',
    details: 'Potential transfer to France via Knights Templar or Othon de la Roche.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1354',
    year: 1354,
    displayDate: '1354 AD',
    title: 'Appearance in Lirey',
    description: 'Appears in possession of Geoffroi de Charny with no documented provenance.',
    category: 'HISTORY',
    consensus: 'SKEPTIC_FAVORED',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1356',
    year: 1356,
    displayDate: '1356 AD',
    title: 'Death of de Charny',
    description: 'Geoffroi de Charny dies at the Battle of Poitiers without revealing how he acquired the Shroud.',
    category: 'HISTORY',
    consensus: 'NEUTRAL',
    details: 'Deepens the mystery of the Shroud\'s sudden appearance in France.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1357',
    year: 1357,
    displayDate: '1357 AD',
    title: 'The Pilgrim Medallion',
    description: 'A lead souvenir medallion found in the Seine depicts the Shroud being displayed by clerics, bearing the arms of Charny and Vergy.',
    category: 'HISTORY',
    consensus: 'NEUTRAL',
    details: 'The earliest undisputed visual record of the Shroud\'s existence in France.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1389',
    year: 1389,
    displayDate: '1389 AD',
    title: 'd\'Arcis Memorandum',
    description: 'Bishop Pierre d\'Arcis claims it is a painting and the artist confessed.',
    category: 'HISTORY',
    consensus: 'SKEPTIC_FAVORED',
    details: 'Skeptics view this as the "smoking gun" of forgery. Authenticists cite financial motives for the claim.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1390',
    year: 1390,
    displayDate: '1390 AD',
    title: 'Bull of Clement VII',
    description: 'Pope Clement VII permits exhibitions but orders that it be proclaimed as a "figure or representation" of the true Shroud.',
    category: 'THEOLOGY',
    consensus: 'SKEPTIC_FAVORED',
    details: 'Often cited by skeptics as official Church recognition of the Shroud as an artistic icon rather than a relic.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1453',
    year: 1453,
    displayDate: '1453 AD',
    title: 'Transfer to House of Savoy',
    description: 'Margaret de Charny gives the Shroud to the House of Savoy in exchange for a castle. She is later excommunicated for the transaction.',
    category: 'HISTORY',
    consensus: 'NEUTRAL',
    details: 'Marks the beginning of the Shroud\'s ownership by the Italian royal family.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1503',
    year: 1503,
    displayDate: '1503 AD',
    title: 'Trial by Water',
    description: 'King Philip I (the Handsome) tests the Shroud\'s authenticity by subjecting it to boiling water/oil tests. The image remains unharmed.',
    category: 'HISTORY',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Used to argue against the painting hypothesis, as pigments would likely wash away or smear.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1532',
    year: 1532,
    displayDate: '1532 AD',
    title: 'Fire of Chambery',
    description: 'Molten silver burns the cloth. Repairs made by Poor Clare nuns.',
    category: 'HISTORY',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Critical for the "Invisible Reweave" theory used to debunk the 1988 C14 dating.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1578',
    year: 1578,
    displayDate: '1578 AD',
    title: 'Arrival in Turin',
    description: 'The Shroud is moved to Turin by the House of Savoy to shorten the pilgrimage for Archbishop Charles Borromeo.',
    category: 'HISTORY',
    consensus: 'NEUTRAL',
    details: 'Establishes the cloth\'s permanent home and its modern name "The Shroud of Turin".',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1898',
    year: 1898,
    displayDate: 'May 28, 1898',
    title: 'The Photonegative Discovery',
    description: 'Secondo Pia\'s photograph reveals the image is a perfect negative.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    imageUrl: 'https://picsum.photos/800/600?grayscale',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1902',
    year: 1902,
    displayDate: '1902',
    title: 'The Delage Scandal',
    description: 'Yves Delage, an agnostic comparative anatomist, presents to the French Academy of Science declaring the image anatomically flawless and authentic. He is censored by the Academy\'s secular secretary.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Delage famously stated: "If the man was not Christ, then who was he?"',
    url: 'https://www.shroud.com/delage.htm',
  },
  {
    id: 'evt_1931',
    year: 1931,
    displayDate: '1931',
    title: 'Enrie Photography',
    description: 'Giuseppe Enrie takes high-resolution orthochromatic photos, confirming Pia\'s findings and revealing microscopic details.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1939',
    year: 1939,
    displayDate: '1939',
    title: 'Hidden from Hitler',
    description: 'The Shroud is secretly moved to the Abbey of Montevergine to protect it from potential Nazi seizure.',
    category: 'HISTORY',
    consensus: 'NEUTRAL',
    details: 'Rumors persisted that Hitler wanted the Shroud for its alleged occult power.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1973',
    year: 1973,
    displayDate: '1973',
    title: 'The Secret Commission',
    description: 'First modern scientific tests. Max Frei discovers pollen. No paint found, but methods were limited.',
    category: 'SCIENCE',
    consensus: 'NEUTRAL',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1976',
    year: 1976,
    displayDate: '1976',
    title: 'VP-8 Image Analysis',
    description: 'John Jackson and Eric Jumper use a VP-8 Image Analyzer at Sandia Labs, discovering the image contains encoded 3D data, unlike normal photographs.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'This discovery directly led to the formation of the STURP team.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1978',
    year: 1978,
    displayDate: 'Oct 1978',
    title: 'STURP Investigation',
    description: '120-hour direct examination. Found no paint, dyes, or brush strokes.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    labId: 'LAB_STURP',
    url: 'https://www.shroud.com/sturp.htm',
  },
  {
    id: 'evt_1981',
    year: 1981,
    displayDate: '1981',
    title: 'STURP Final Report',
    description: 'Official summary released: "The Shroud image is that of a real human form of a scourged, crucified man. It is not the product of an artist."',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Concluded that no known chemical or artistic method could account for the image.',
    url: 'https://www.shroud.com/78conclu.htm',
  },
  {
    id: 'evt_1983',
    year: 1983,
    displayDate: '1983',
    title: 'Transfer to Holy See',
    description: 'Upon his death, ex-King Umberto II of Italy bequeaths the Shroud to the Pope, ending centuries of Savoy ownership.',
    category: 'HISTORY',
    consensus: 'NEUTRAL',
    details: 'Legal ownership formally transferred to the Vatican.',
    url: 'https://www.shroud.com/history.htm',
  },
  {
    id: 'evt_1986',
    year: 1986,
    displayDate: '1986',
    title: 'The Turin Protocol Breach',
    description: 'A predefined scientific protocol calling for 7 labs and 2 dating methods was discarded in favor of just 3 labs using 1 method (AMS).',
    category: 'SCIENCE',
    consensus: 'CONTESTED',
    details: 'Critics argue this protocol change reduced statistical rigor and eliminated cross-checks.',
    url: 'https://www.shroud.com/pdfs/marinobenford.pdf',
  },
  {
    id: 'evt_1988',
    year: 1988,
    displayDate: 'Oct 13, 1988',
    title: 'C-14 Radiocarbon Dating',
    description: 'Three labs date the cloth to 1260-1390 AD.',
    category: 'SCIENCE',
    consensus: 'SKEPTIC_FAVORED',
    labId: 'LAB_OXFORD',
    details: 'The primary evidence for the medieval forgery hypothesis.',
    url: 'https://www.nature.com/articles/337611a0',
  },
  {
    id: 'evt_1997',
    year: 1997,
    displayDate: 'Apr 11, 1997',
    title: 'Guarini Chapel Fire',
    description: 'Fireman Mario Trematore rescues the Shroud from a catastrophic fire in the Turin Cathedral.',
    category: 'HISTORY',
    consensus: 'NEUTRAL',
    url: 'https://www.shroud.com/fire.htm',
  },
  {
    id: 'evt_2002',
    year: 2002,
    displayDate: '2002',
    title: 'The "Restoration"',
    description: 'Backing cloth removed and patches taken off. Critics argue this destroyed chemical data and altered the cloth\'s tension.',
    category: 'HISTORY',
    consensus: 'NEUTRAL',
    details: 'Mechtild Flury-Lemberg led the preservation effort.',
    url: 'https://www.shroud.com/restor.htm',
  },
  {
    id: 'evt_2004',
    year: 2004,
    displayDate: '2004',
    title: 'Reverse Side Image Discovery',
    description: 'Fanti and Maggiolo discover a faint face image on the back side of the cloth using image processing.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Implies a directional formation mechanism that affected both sides but not the center of the linen.',
    url: 'https://www.shroud.com/pdfs/doc0000.pdf',
  },
  {
    id: 'evt_2005',
    year: 2005,
    displayDate: 'Jan 2005',
    title: 'Ray Rogers Rebuttal',
    description: 'Proved C-14 sample contained cotton and dye (reweave), unlike main cloth.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    labId: 'LAB_LANL',
    url: 'https://www.shroud.com/pdfs/rogers2.pdf',
  },
  {
    id: 'evt_2009',
    year: 2009,
    displayDate: '2009',
    title: 'The "Death Certificate"',
    description: 'Vatican researcher Barbara Frale claims to decipher faint writing on the Shroud referencing "Jesus the Nazarene" using computer enhancement.',
    category: 'HISTORY',
    consensus: 'CONTESTED',
    details: 'Highly controversial; many experts consider the "writing" to be pareidolia or weave noise.',
    url: 'https://www.shroud.com/pdfs/frale.pdf',
  },
  {
    id: 'evt_2010',
    year: 2010,
    displayDate: '2010',
    title: 'ENEA VUV Radiation',
    description: 'Calculated 34 billion watts of VUV light needed to create the image.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    labId: 'LAB_ENEA',
    url: 'https://www.enea.it/en/news-enea/news/the-shroud-of-turin-and-the-enea-study',
  },
  {
    id: 'evt_2013',
    year: 2013,
    displayDate: '2013',
    title: 'Padua Spectroscopy Dating',
    description: 'Giulio Fanti uses FTIR and Raman spectroscopy to date fibers to 300 BC - 400 AD.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    labId: 'LAB_PADUA',
    url: 'https://www.shroud.com/pdfs/fanti-ftir.pdf',
  },
  {
    id: 'evt_2014',
    year: 2014,
    displayDate: '2014',
    title: 'Earthquake Neutron Theory',
    description: 'Carpinteri et al. propose that a high-magnitude earthquake in 33 AD released piezonuclear neutrons, altering the nitrogen in the cloth to C-14.',
    category: 'SCIENCE',
    consensus: 'UNVERIFIED',
    details: 'Attempts to explain the 1260 AD date via natural neutron irradiation.',
    url: 'https://link.springer.com/article/10.1007/s11004-013-9513-x',
  },
  {
    id: 'evt_2015',
    year: 2015,
    displayDate: 'Oct 2015',
    title: 'DNA Sequencing Study',
    description: 'Gianni Barcaccia sequences DNA from dust particles, finding plant DNA from South America, Middle East, Asia, and Europe.',
    category: 'SCIENCE',
    consensus: 'NEUTRAL',
    details: 'Suggests the cloth has been contaminated by travel or visitors from around the world.',
    url: 'https://www.nature.com/articles/srep14484',
  },
  {
    id: 'evt_2017',
    year: 2017,
    displayDate: 'Jul 2017',
    title: 'Blood Nanoparticles Study',
    description: 'Carlino et al. find high levels of creatinine and ferritin, indicating severe trauma.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    url: 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0180487',
  },
  {
    id: 'evt_2018',
    year: 2018,
    displayDate: 'Jul 2018',
    title: 'BPA (Blood Pattern Analysis)',
    description: 'Matteo Borrini and Luigi Garlaschelli use forensic techniques to show blood flows are inconsistent with a crucified body.',
    category: 'SCIENCE',
    consensus: 'SKEPTIC_FAVORED',
    details: 'They argued the "belt of blood" on the lower back would not form on a supine body.',
    url: 'https://onlinelibrary.wiley.com/doi/abs/10.1111/1556-4029.13867',
  },
  {
    id: 'evt_2019',
    year: 2019,
    displayDate: '2019',
    title: 'Casabianca Statistical Analysis',
    description: 'Tristan Casabianca publishes analysis of raw 1988 C14 data released via legal request, revealing significant heterogeneity between labs that was not originally reported.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    details: 'Suggests the carbon dating results were not statistically reliable due to contamination or stratification.',
    url: 'https://onlinelibrary.wiley.com/doi/abs/10.1111/1556-4029.14020',
  },
  {
    id: 'evt_2022',
    year: 2022,
    displayDate: 'Apr 2022',
    title: 'WAXS Dating Study',
    description: 'X-ray scattering dates cellulose degradation to 1st Century AD.',
    category: 'SCIENCE',
    consensus: 'AUTHENTIC_FAVORED',
    labId: 'LAB_CNR',
    url: 'https://www.mdpi.com/2079-4991/12/2/222',
  },
  {
    id: 'evt_2025',
    year: 2025,
    displayDate: '2025',
    title: '3D Bas-Relief Study',
    description: 'Cicero Moraes simulates image formation via bas-relief sculpture.',
    category: 'SCIENCE',
    consensus: 'SKEPTIC_FAVORED',
    labId: 'LAB_MORAES',
    url: 'https://www.researchgate.net/publication/366586043_The_Shroud_of_Turin_Unveiled_A_Forensic_Review',
  }
];

export const LABS: LabModule[] = [
  {
    id: 'LAB_STURP',
    name: 'STURP (Shroud of Turin Research Project)',
    year: 1978,
    researcher: 'Multiple (US Team)',
    methodology: 'X-Ray Fluorescence, VP-8 Analyzer, Tape Lifts',
    findings: 'Image is superficial (0.2 microns). No pigments. Contains 3D distance information.',
    lens: 'BELIEVER',
    url: 'https://www.shroud.com/sturp.htm'
  },
  {
    id: 'LAB_MCCRONE',
    name: 'McCrone Associates',
    year: 1979,
    researcher: 'Walter McCrone',
    methodology: 'Polarized Light Microscopy',
    findings: 'Identified iron oxide and mercuric sulfide (vermilion). Concluded image is a painting.',
    lens: 'SKEPTIC',
    url: 'https://www.mccrone.com/mm/the-shroud-of-turin/'
  },
  {
    id: 'LAB_HELLER',
    name: 'New England Institute',
    year: 1981,
    researcher: 'Heller & Adler',
    methodology: 'Chemical & Microspectrophotometric Analysis',
    findings: 'Confirmed presence of hemoglobin, albumin, and high bilirubin levels. No paint binder found.',
    lens: 'BELIEVER',
    url: 'https://www.shroud.com/pdfs/heller1.pdf'
  },
  {
    id: 'LAB_OXFORD',
    name: 'Radiocarbon Consortium',
    year: 1988,
    researcher: 'Oxford, Arizona, Zurich Labs',
    methodology: 'Accelerator Mass Spectrometry (AMS)',
    findings: '95% confidence date of 1260-1390 AD. Consistent with d\'Arcis Memo.',
    lens: 'SKEPTIC',
    url: 'https://www.nature.com/articles/337611a0'
  },
  {
    id: 'LAB_LANL',
    name: 'Los Alamos National Lab',
    year: 2005,
    researcher: 'Ray Rogers',
    methodology: 'Thermochimica Analysis',
    findings: 'Vanillin analysis shows C14 sample was chemically distinct (newer) than main cloth.',
    lens: 'BELIEVER',
    url: 'https://www.shroud.com/pdfs/rogers2.pdf'
  },
  {
    id: 'LAB_FREI',
    name: 'Zurich Police Scientific Service',
    year: 1973,
    researcher: 'Max Frei',
    methodology: 'Palynology (Pollen Analysis) via Tape Lifts',
    findings: 'Identified 58 pollen types, 75% of which are native to the Near East (Israel, Turkey), supporting a historical path through Edessa and Jerusalem.',
    lens: 'BELIEVER',
    url: 'https://www.shroud.com/pdfs/kohlbeck.pdf'
  },
  {
    id: 'LAB_PADUA',
    name: 'University of Padua',
    year: 2013,
    researcher: 'Giulio Fanti',
    methodology: 'FT-IR and Raman Spectroscopy',
    findings: 'Mechanical and chemical testing of fibers suggests a date range of 300 BC to 400 AD.',
    lens: 'BELIEVER',
    url: 'https://www.shroud.com/pdfs/fanti-ftir.pdf'
  },
  {
    id: 'LAB_CNR',
    name: 'Institute of Crystallography (CNR)',
    year: 2022,
    researcher: 'Liberato De Caro',
    methodology: 'WAXS (Wide-Angle X-ray Scattering)',
    findings: 'Crystal structure degradation matches Masada linen (55-74 AD).',
    lens: 'BELIEVER',
    url: 'https://www.mdpi.com/2079-4991/12/2/222'
  },
  {
    id: 'LAB_MORAES',
    name: 'Independent Forensic Lab',
    year: 2025,
    researcher: 'Cicero Moraes',
    methodology: '3D Photogrammetry & Blender Simulation',
    findings: 'Image distortions match a cloth draped over a low-relief sculpture, not a body.',
    lens: 'SKEPTIC',
    url: 'https://www.researchgate.net/publication/366586043_The_Shroud_of_Turin_Unveiled_A_Forensic_Review'
  }
];

export const VIRAL_CLAIMS: ViralClaim[] = [
  {
    id: 'claim_resurrection',
    title: 'The Shroud image proves the Resurrection.',
    origin: 'Dr. Jeremiah Johnston / Tucker Carlson Interview',
    description: 'The claim relies on ENEA calculations (2010) requiring 34 billion watts of VUV radiation to replicate the image depth. While physics allows for this formation mechanism, science cannot verify the source of that radiation was supernatural. It remains a "Singularity" in the data.',
    verdict: 'PLAUSIBLE',
    verdictText: 'Plausible Hypothesis / Unproven',
    url: 'https://www.enea.it/en/news-enea/news/the-shroud-of-turin-and-the-enea-study',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_blood_first',
    title: 'There is no image under the blood.',
    origin: 'STURP Findings (1978)',
    description: 'STURP chemical analysis confirmed that blood serum saturated the cloth before the image formation process occurred. The image fibrils stop at the edge of bloodstains, contradicting the "painting" hypothesis where blood would be applied over paint.',
    verdict: 'VERIFIED',
    verdictText: 'Verified by Forensic Chemistry',
    url: 'https://www.shroud.com/78conclu.htm',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_twist',
    title: 'Z-Twist vs S-Twist Yarn',
    origin: 'Textile Historians',
    description: 'The Shroud linen is spun with a "Z-twist" (clockwise), typical of cotton or medieval European linen. Linen from 1st-century Judea (e.g., Masada) is predominantly "S-twist" (counter-clockwise).',
    verdict: 'CONTESTED',
    verdictText: 'Inconsistent with local archaeology',
    lens: 'SKEPTIC'
  },
  {
    id: 'claim_sudarium',
    title: 'The Sudarium of Oviedo matches the Shroud.',
    origin: 'Dr. Mark Guscin',
    description: 'The Sudarium (face cloth kept in Spain) has a documented history back to 614 AD. It contains Type AB blood and stain patterns that geometrically align with the Shroud, suggesting both covered the same face.',
    verdict: 'VERIFIED',
    verdictText: 'Verified Congruence / Provenance Established',
    url: 'https://www.shroud.com/guscin.htm',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_thumbs',
    title: 'The thumbs are missing (Median Nerve).',
    origin: 'Dr. Pierre Barbet',
    description: 'The image shows hands with no visible thumbs. Barbet demonstrated that nails driven through the wrist (Space of Destot) damage the median nerve, causing the thumbs to retract into the palm—a detail unknown to medieval artists.',
    verdict: 'VERIFIED',
    verdictText: 'Anatomically Accurate',
    url: 'https://www.shroud.com/barbet.htm',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_harrington',
    title: 'Dr. Robert Harrington, a skeptic, converted after studying the Shroud.',
    origin: 'Internet Viral Text / Sermons',
    description: 'There is no record of a "Dr. Robert Harrington" in the official STURP roster or major peer-reviewed Shroud literature. This likely conflates Dr. John Heller (STURP blood chemist) or Barrie Schwortz (STURP photographer) with Robert Sutton Harrington (Astronomer).',
    verdict: 'UNVERIFIED',
    verdictText: 'Unverified Anecdote / Likely Fabrication',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_nasa_3d',
    title: 'NASA scientists found a 3D face on the Shroud.',
    origin: 'Jackson & Jumper (VP-8 Image Analyzer)',
    description: 'STURP scientists used a VP-8 analyzer (designed for planetary topography) which translated image intensity into vertical relief. The Shroud yielded a perfect 3D relief, unlike standard photographs which distort into nose-heavy chaos. This confirms the image intensity correlates to distance from the body.',
    verdict: 'VERIFIED',
    verdictText: 'Verified Data / Interpretation Debated',
    url: 'https://www.shroud.com/history.htm#sturp',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_davinci',
    title: 'Leonardo da Vinci forged the Shroud.',
    origin: 'Lynn Picknett & Clive Prince',
    description: 'A popular theory suggesting Da Vinci used proto-photography. However, the Shroud was historically documented in Lirey (1354) and Chambery (1532) long before Leonardo was born (1452).',
    verdict: 'DEBUNKED',
    verdictText: 'Historically Impossible',
    url: 'https://www.history.com/news/shroud-turin-leonardo-da-vinci-forgery-theory',
    lens: 'SKEPTIC'
  },
  {
    id: 'claim_swoon',
    title: 'The man in the Shroud was not dead (Swoon Theory).',
    origin: '19th Century Rationalists',
    description: 'Suggests Jesus survived the cross and the cloth captured his sweat/healing herbs. Medical analysis of the blood (post-mortem separation) and rigor mortis posture contradicts this.',
    verdict: 'DEBUNKED',
    verdictText: 'Contradicted by Pathology',
    lens: 'SKEPTIC'
  },
  {
    id: 'claim_scorch',
    title: 'The image is a scorch from a hot statue.',
    origin: 'Geoffrey Ashe / Shadow of the Shroud',
    description: 'Theory that a heated metal bas-relief created the image. However, scorches fluoresce under UV light; the Shroud body image does not, though the 1532 burn marks do.',
    verdict: 'DEBUNKED',
    verdictText: 'Fails UV Fluorescence Test',
    lens: 'SKEPTIC'
  },
  {
    id: 'claim_flagrum',
    title: 'Wounds match Roman Flagrum.',
    origin: 'Forensic Pathologists (Bucklin, Zugibe)',
    description: 'The body is covered in dumbbell-shaped contusions. These match the lead weights (plumbatae) used in the Roman flagrum. The angle of the marks suggests two executioners of different heights.',
    verdict: 'VERIFIED',
    verdictText: 'Consistent with Roman Archaeology',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_coins',
    title: 'Roman coins (Leptons) are visible over the eyes.',
    origin: 'Father Filas / Alan Whanger',
    description: 'Some researchers claim to see letters "UCAI" (from "Tiberiou Kaisaros") on coins over the eyes in high-contrast photos. Skeptics and many authenticists argue this is pareidolia (seeing patterns in random noise) due to the weave texture.',
    verdict: 'CONTESTED',
    verdictText: 'Highly Contested / Pareidolia',
    url: 'https://www.shroud.com/pdfs/whanger.pdf',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_pollen',
    title: 'Pollen from plants unique to Jerusalem found on the cloth.',
    origin: 'Max Frei (Criminologist)',
    description: 'Frei identified pollen grains (Gundelia tournefortii) native to the Near East. While later criticized for contamination protocols, subsequent studies (Avinoam Danin) supported the floral imagery claims.',
    verdict: 'CONTESTED',
    verdictText: 'Contested Evidence',
    url: 'https://www.shroud.com/pdfs/danin2.pdf',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_neutron',
    title: 'Neutron Flux / Isotope Enrichment',
    origin: 'Thomas J. Phillips (Physicist)',
    description: 'A theory proposing that the Resurrection event released a burst of neutrons, which converted some Nitrogen-14 in the cloth into Carbon-14, making the cloth appear younger (medieval) during carbon dating.',
    verdict: 'UNVERIFIED',
    verdictText: 'Theoretical Physics / No Lab Evidence',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_gothic',
    title: 'The figure fits Gothic art proportions.',
    origin: 'Art Historians',
    description: 'Skeptics argue the elongated body (very tall, thin fingers) matches 14th-century Gothic artistic trends rather than the physiology of a 1st-century Semitic man.',
    verdict: 'PLAUSIBLE',
    verdictText: 'Consistent with Art History',
    lens: 'SKEPTIC'
  },
  {
    id: 'claim_maillard',
    title: 'Maillard Reaction (Naturalistic Theory)',
    origin: 'Ray Rogers (STURP)',
    description: 'A chemical reaction between amine vapors from the body and the saponaria/starch impurities on the surface of the linen, creating a superficial yellow-brown image without radiation or painting.',
    verdict: 'PLAUSIBLE',
    verdictText: 'Chemically Plausible / Explains Color',
    url: 'https://www.shroud.com/pdfs/rogers2.pdf',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_dematerialization',
    title: 'Cloth Collapse / Dematerialization',
    origin: 'Dr. John Jackson (STURP)',
    description: 'The theory that the body became mechanically transparent (dematerialized), causing the cloth to collapse *through* the body while emitting radiation. This explains why the side images are not distorted laterally.',
    verdict: 'UNVERIFIED',
    verdictText: 'Physically Theoretical / Untestable',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_reweave',
    title: 'The "Invisible Reweave" Hypothesis',
    origin: 'Benford & Marino',
    description: 'Proposes that the corner sample used for 1988 dating was a skilled 16th-century "French Reweave" repair using dyed cotton, which skewed the C14 date to the medieval period. Ray Rogers confirmed the presence of dye and cotton in that specific area.',
    verdict: 'PLAUSIBLE',
    verdictText: 'Supported by Chemical Analysis',
    url: 'https://www.shroud.com/pdfs/rogers2.pdf',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_volckringer',
    title: 'Volckringer Patterns',
    origin: 'Jean Volckringer',
    description: 'Observations that dried plants pressed in books for decades create negative images with 3D qualities similar to the Shroud, supporting a naturalistic chemical model (acid oxidation) over time.',
    verdict: 'PLAUSIBLE',
    verdictText: 'Natural Analogue Exists',
    lens: 'SKEPTIC'
  },
  {
    id: 'claim_orthographic',
    title: 'Vertical Mapping / Orthographic Projection',
    origin: 'Dr. John Jackson',
    description: 'The body image does not show the geometric distortion expected if a cloth was wrapped around a 3D body (e.g. ears far apart). Instead, it appears as a vertical projection (scanner-like), suggesting radiation traveling in straight lines.',
    verdict: 'VERIFIED',
    verdictText: 'Geometrically Verified',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_proto_photo',
    title: 'Proto-Photography (Shadow Hypothesis)',
    origin: 'Nicholas Allen',
    description: 'Theory that a medieval artist used a camera obscura with a quartz lens and silver sulfate/ammonia to create a primitive photograph. It explains the negative quality but lacks historical evidence for the technology.',
    verdict: 'PLAUSIBLE',
    verdictText: 'Feasible Physics / Historical Anachronism',
    lens: 'SKEPTIC'
  },
  {
    id: 'claim_laser',
    title: 'Excimer Laser Radiation',
    origin: 'ENEA (Dr. Di Lazzaro)',
    description: 'Short bursts of ArF excimer laser (UV) successfully replicated the depth and color of the Shroud image on linen, suggesting a burst of directional energy.',
    verdict: 'PLAUSIBLE',
    verdictText: 'Physically Replicable with Modern Tech',
    url: 'https://www.enea.it/en/news-enea/news/the-shroud-of-turin-and-the-enea-study',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_bioplastic',
    title: 'Bioplastic Coating (Bacterial Layer)',
    origin: 'Dr. Leoncio Garza-Valdes',
    description: 'Theory that a layer of "bioplastic" varnish created by bacteria and fungi on the cloth added younger carbon to the sample, skewing the C14 date by centuries. Cleaning protocols may not have removed this molecular layer.',
    verdict: 'PLAUSIBLE',
    verdictText: 'Microbiologically Plausible',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_acid_paint',
    title: 'Acid Pigmentation / Painting on Glass',
    origin: 'Luigi Garlaschelli (2009)',
    description: 'Garlaschelli reproduced a Shroud-like image by applying acid pigment to a cloth draped over a volunteer, then heating it. It replicated the negative image but lacked the microscopic superficiality and 3D precision.',
    verdict: 'PLAUSIBLE',
    verdictText: 'Replicated Macroscopic Appearance',
    lens: 'SKEPTIC'
  },
  {
    id: 'claim_negative_difficulty',
    title: 'Impossibility of Negative Painting',
    origin: 'Leo Vala (Photographer)',
    description: 'To paint a perfect negative (where light is dark and dark is light) requires the artist to mentally invert every value. Doing this flawlessly for a life-sized figure before the invention of photography is considered cognitively impossible.',
    verdict: 'PLAUSIBLE',
    verdictText: 'Cognitively Implausible for Medieval Artist',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_hyper_realism',
    title: 'Anatomical Hyper-Realism',
    origin: 'Dr. Yves Delage',
    description: 'The image contains subtle anatomical details (e.g., specific muscle contractions, blood flow gravity) that were unknown to medieval medicine and art, yet are forensically correct for a crucified body.',
    verdict: 'VERIFIED',
    verdictText: 'Forensically Accurate',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_blood_type',
    title: 'Blood Type AB',
    origin: 'Dr. Baima Bollone',
    description: 'Immunological tests identify the blood as Type AB. This matches the Sudarium of Oviedo and reported Eucharistic miracles, though DNA degradation makes certainty difficult.',
    verdict: 'VERIFIED',
    verdictText: 'Serologically Consistent',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_blood_flow',
    title: 'Blood Flow Gravity',
    origin: 'Dr. Pierre Barbet',
    description: 'Angles of blood streams on the wrists and arms align with gravity at specific angles (65 degrees), consistent with a body slumping and raising on a cross to breathe.',
    verdict: 'VERIFIED',
    verdictText: 'Consistent with Crucifixion Mechanics',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_hair_style',
    title: 'Long Hair Controversy',
    origin: 'Biblical Historians',
    description: 'Skeptics note St. Paul (1 Cor 11) calls long hair on men "shameful," suggesting 1st-century Jews had short hair. Authenticists cite the Nazarite vow or non-conformity.',
    verdict: 'CONTESTED',
    verdictText: 'Cultural Ambiguity',
    lens: 'SKEPTIC'
  },
  {
    id: 'claim_no_decomp',
    title: 'No Signs of Decomposition',
    origin: 'Dr. Robert Bucklin (Pathologist)',
    description: 'Forensic pathology finds no evidence of putrefaction (decomposition gases like ammonia) on the cloth. This implies the body was removed within 40 hours of death.',
    verdict: 'VERIFIED',
    verdictText: 'Pathologically Consistent',
    lens: 'BELIEVER'
  },
  {
    id: 'claim_burial_customs',
    title: 'Jewish Burial Customs (Sindon vs. Othonia)',
    origin: 'Biblical Scholars',
    description: 'Debate centers on whether John\'s Gospel ("othonia" - strips) contradicts the Synoptics ("sindon" - single sheet). Authenticists argue "othonia" can mean "grave clothes" generally.',
    verdict: 'CONTESTED',
    verdictText: 'Linguistic Ambiguity',
    lens: 'SKEPTIC'
  }
];

export const ARTIFACT_HOTSPOTS: ArtifactHotspot[] = [
  {
    id: 'spot_forehead',
    x: 48,
    y: 28,
    label: 'The "Epsilon" Stain',
    description: 'A reverse-3 shaped blood stain on the forehead. Authenticists link this to a specific vein. Skeptics argue it looks painted.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_crown',
    x: 48,
    y: 18,
    label: 'Puncture Wounds',
    description: 'Numerous small puncture wounds around the scalp consistent with a cap of thorns, not a circlet/crown as depicted in European art.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_cheek',
    x: 60,
    y: 45,
    label: 'Cheek Swelling',
    description: 'The right cheek appears swollen, consistent with a severe beating as described in the Passion narratives.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_surface',
    x: 65,
    y: 55,
    label: 'Superficiality',
    description: 'The image color exists only on the topmost fibers (0.2 microns thick). It does not penetrate the thread or capillary spaces, ruling out liquids or dyes.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_nose',
    x: 49,
    y: 42,
    label: 'Nasal Deviation',
    description: 'Possible deviation of the nasal septum, suggesting a blow to the face.',
    lens: 'NEUTRAL'
  },
  {
    id: 'spot_weave',
    x: 80,
    y: 80,
    label: 'Herringbone Weave',
    description: 'A complex 3:1 herringbone twill weave. Rare for the 1st Century, but extant samples exist (e.g., Masada). Common in medieval silk.',
    lens: 'NEUTRAL'
  },
  {
    id: 'spot_ears',
    x: 30,
    y: 40,
    label: 'Missing Ears',
    description: 'The hair falls straight down, obscuring the ears. Skeptics note this style is typical of Gothic art but unusual for a supine body where hair would fall back.',
    lens: 'SKEPTIC'
  },
  {
    id: 'spot_neck',
    x: 50,
    y: 65,
    label: 'Neck Separation',
    description: 'There is a clear line separating the head from the body. Some critics argue this indicates the head was painted separately or is a mask.',
    lens: 'SKEPTIC'
  },
  {
    id: 'spot_fold',
    x: 50,
    y: 75,
    label: 'The "Tetradiplon" Line',
    description: 'Faint fold marks suggest the cloth was once folded 4 times, showing only the face. This matches historical descriptions of the "Image of Edessa".',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_beard',
    x: 50,
    y: 58,
    label: 'Bifurcated Beard',
    description: 'The beard appears to be split or forked slightly off-center. Skeptics argue this mimics Byzantine iconography (Pantocrator), while authenticists note it matches Nazareth burial customs.',
    lens: 'NEUTRAL'
  },
  {
    id: 'spot_teeth',
    x: 50,
    y: 51,
    label: 'Teeth & Roots',
    description: 'Some researchers (e.g., Dr. Whanger) claim to identify teeth and roots through the skin, suggesting an "X-Ray" effect caused by high-energy radiation.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_hair_blood',
    x: 72,
    y: 35,
    label: 'Blood Flow in Hair',
    description: 'Blood trickles into the hair but appears to flow vertically as if standing, rather than matting into the hair as expected for a supine body.',
    lens: 'SKEPTIC'
  },
  {
    id: 'spot_water',
    x: 15,
    y: 15,
    label: 'Water Stains',
    description: 'Diamond-shaped water stains from the 1532 fire. These clearly overlay the body image, proving the image formation predates the 16th-century fire.',
    lens: 'NEUTRAL'
  },
  {
    id: 'spot_eyebrow',
    x: 42,
    y: 36,
    label: 'Eyebrow Wound',
    description: 'The left eyebrow appears to have a laceration or abrasion, consistent with a fall or strike to the face.',
    lens: 'BELIEVER'
  },
   {
    id: 'spot_light',
    x: 85,
    y: 60,
    label: 'No Light Focus',
    description: 'Photography requires a lens to focus light. This image has no focal point and no directionality of light (no shadows), acting more like a distance-map.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_coin',
    x: 58,
    y: 38,
    label: 'Lepton Coin',
    description: '3D analysis suggests a button-like object over the right eye. Some claim it matches a Pontius Pilate lepton (29 AD), though resolution is low.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_limestone',
    x: 49,
    y: 46, 
    label: 'Travertine Dust',
    description: 'Traces of aragonite limestone found on the nose match the mineral signature of tombs in Jerusalem, distinct from Turin or France.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_serum',
    x: 52,
    y: 25,
    label: 'Serum Retraction',
    description: 'Bloodstains show a halo of clear serum under UV light. This separation occurs in coagulating blood but is difficult to replicate with paint.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_bilirubin',
    x: 55,
    y: 30,
    label: 'High Bilirubin',
    description: 'The blood remains red rather than turning black/brown. Dr. Adler attributed this to high bilirubin levels caused by extreme physical trauma before death.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_banding',
    x: 10,
    y: 40,
    label: 'Yarn Banding',
    description: 'Subtle horizontal bands in the linen suggest different batches of yarn were used, a quality issue consistent with large-scale ancient or medieval looms.',
    lens: 'SKEPTIC'
  },
  {
    id: 'spot_outline',
    x: 68,
    y: 50,
    label: 'No Outline',
    description: 'The image has no distinct edges or borders. Unlike a painting where brushstrokes create lines, the Shroud image simply fades into the background.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_hair_stiffness',
    x: 35,
    y: 35,
    label: 'Rigid Hair',
    description: 'The hair stands stiffly on the sides of the face rather than falling back. Skeptics see this as "bad art", while believers argue it indicates rigor mortis.',
    lens: 'NEUTRAL'
  },
  {
    id: 'spot_flowers',
    x: 22,
    y: 32,
    label: 'Flower Images',
    description: 'Researchers like Danin claim to identify images of Chrysanthemum coronarium (native to Jerusalem) around the head area.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_chin_band',
    x: 50,
    y: 62,
    label: 'Chin Band',
    description: 'A faint band across the chin is interpreted by some as a cloth tied to keep the jaw closed, a Jewish burial custom.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_mirror',
    x: 40,
    y: 45,
    label: 'Mirror Reversal',
    description: 'The image is laterally inverted (left side of body is on right side of image). This happens naturally in contact imprints but is counter-intuitive for an artist painting a portrait.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_seam',
    x: 90,
    y: 10,
    label: 'Side Strip',
    description: 'A strip of cloth (~8cm wide) is sewn longitudinally along the side. This may indicate the use of a specific professional loom width common in the 1st Century.',
    lens: 'NEUTRAL'
  },
  {
    id: 'spot_poker',
    x: 25,
    y: 25,
    label: 'L-Shaped Holes',
    description: 'Four "poker holes" in an L-pattern that predate the 1532 fire. These distinct burn marks appear in the 1192 Pray Codex, proving the Shroud existed then.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_burns',
    x: 10,
    y: 70,
    label: 'Burn Marks (1532)',
    description: 'Charred areas from the fire. Unlike the body image, these burns fluoresce under UV light, chemically distinguishing the image formation from heat scorching.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_triangle',
    x: 49,
    y: 35,
    label: 'Vignon Triangle',
    description: 'A distinctive open triangle shape on the bridge of the nose. This feature appears in Byzantine icons (e.g., Pantocrator) starting 6th Century, suggesting they were copied from the Shroud.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_lip',
    x: 50,
    y: 54,
    label: 'Lip Trauma',
    description: 'The upper lip is swollen and possibly lacerated, suggesting a violent blow to the face, aligning with the Passion narrative.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_right_eye',
    x: 40,
    y: 35,
    label: 'Right Eye Contusion',
    description: 'The area around the right eye (left on image) is swollen and bruised, indicating blunt force trauma.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_thumbs',
    x: 48,
    y: 72,
    label: 'Hidden Thumbs',
    description: 'The thumbs are retracted into the palms. This reaction occurs when the median nerve is damaged by a nail through the wrist, a detail anatomically correct but unknown to medieval artists.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_shoulder',
    x: 38,
    y: 42,
    label: 'Shoulder Abrasions',
    description: 'Bruising and abrasions on the shoulder blade area, consistent with carrying a heavy, rough object like the patibulum (crossbeam).',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_parting',
    x: 50,
    y: 15,
    label: 'Center Hair Part',
    description: 'The hair is parted down the middle. While common in medieval art, historical debate continues regarding its prevalence in 1st-century Judea.',
    lens: 'NEUTRAL'
  },
  {
    id: 'spot_pigments',
    x: 45,
    y: 30,
    label: 'Red Ochre Particles',
    description: 'Walter McCrone identified particles of iron oxide and vermilion pigment in the blood areas, concluding the image is a painting. Other labs disputed this as contamination.',
    lens: 'SKEPTIC'
  },
  {
    id: 'spot_lance',
    x: 42,
    y: 68,
    label: 'Lance Wound',
    description: 'Elliptical wound on the right side of the chest (left on image) corresponding to the spear thrust. Shows blood and clear serum (pericardial fluid).',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_wrist',
    x: 52,
    y: 70,
    label: 'Wrist Wound',
    description: 'Blood flow on the wrist area indicates the nail was driven through the Destot space, not the palm, which would tear under body weight.',
    lens: 'BELIEVER'
  },
  {
    id: 'spot_knee',
    x: 55,
    y: 85,
    label: 'Left Knee Contusion',
    description: 'The left knee area shows significant abrasion and microscopic dirt, consistent with a fall on a hard surface while carrying a heavy weight.',
    lens: 'BELIEVER'
  }
];

// STURP Published Papers - Source: https://www.shroud.com/78papers.htm
export const STURP_PAPERS: STURPPaper[] = [
  { id: 1, authors: 'Accetta, J.S. and J.S. Baumgart', title: 'Infrared Reflectance Spectroscopy and Thermographic Investigations of the Shroud of Turin', publication: 'Applied Optics, Vol. 19, No. 12, pp. 1921-1929', year: 1980, pdfUrl: 'https://www.shroud.com/pdfs/accetta.pdf', category: 'REFEREED' },
  { id: 2, authors: 'Avis, C., D. Lynn, J. Lorre, S. Lavoie, J. Clark, E. Armstrong, and J. Addington', title: 'Image Processing of the Shroud of Turin', publication: 'IEEE 1982 Proceedings of the International Conference on Cybernetics and Society, pp. 554-558', year: 1982, pdfUrl: 'https://www.shroud.com/pdfs/avis.pdf', category: 'REFEREED' },
  { id: 3, authors: 'Devan, D. and V. Miller', title: 'Quantitative Photography of the Shroud of Turin', publication: 'IEEE 1982 Proceedings of the International Conference on Cybernetics and Society, pp. 548-553', year: 1982, pdfUrl: 'https://www.shroud.com/pdfs/devan.pdf', category: 'REFEREED' },
  { id: 4, authors: 'Ercoline, W.R., R.C. Downs, Jr. and J.P. Jackson', title: 'Examination of the Turin Shroud for Image Distortions', publication: 'IEEE 1982 Proceedings of the International Conference on Cybernetics and Society, pp. 576-579', year: 1982, pdfUrl: 'https://www.shroud.com/pdfs/ercoline.pdf', category: 'REFEREED' },
  { id: 5, authors: 'Gilbert, R., Jr. and M.M. Gilbert', title: 'Ultraviolet-Visible Reflectance and Fluorescence Spectra of the Shroud of Turin', publication: 'Applied Optics, Vol. 19, No. 12, pp. 1930-1936', year: 1980, pdfUrl: 'https://www.shroud.com/pdfs/gilbert.pdf', category: 'REFEREED' },
  { id: 6, authors: 'Heller, J.H. and A.D. Adler', title: 'Blood on the Shroud of Turin', publication: 'Applied Optics, Vol. 19, No. 16, pp. 2742-2744', year: 1980, pdfUrl: 'https://www.shroud.com/pdfs/heller.pdf', category: 'REFEREED' },
  { id: 7, authors: 'Heller, J.H. and A.D. Adler', title: 'A Chemical Investigation of the Shroud of Turin', publication: 'Canadian Society of Forensic Sciences Journal, Vol. 14, No. 3, pp. 81-103', year: 1981, pdfUrl: 'https://www.shroud.com/pdfs/chemical.pdf', category: 'REFEREED' },
  { id: 8, authors: 'Jackson, J.P., E.J. Jumper and W.R. Ercoline', title: 'Three Dimensional Characteristic of the Shroud Image', publication: 'IEEE 1982 Proceedings of the International Conference on Cybernetics and Society, pp. 559-575', year: 1982, pdfUrl: 'https://www.shroud.com/pdfs/3d.pdf', category: 'REFEREED' },
  { id: 9, authors: 'Jackson, J.P., E.J. Jumper, and W.R. Ercoline', title: 'Correlation of Image Intensity on the Turin Shroud with the 3-D Structure of a Human Body Shape', publication: 'Applied Optics, Vol. 23, No. 14, pp. 2244-2270', year: 1984, pdfUrl: 'https://www.shroud.com/pdfs/jackson.pdf', category: 'REFEREED' },
  { id: 10, authors: 'Jumper, E.J. and R.W. Mottern', title: 'Scientific Investigation of the Shroud of Turin', publication: 'Applied Optics, Vol. 19, No. 12, pp. 1909-1912', year: 1980, pdfUrl: 'https://www.shroud.com/pdfs/jumper.pdf', category: 'REFEREED' },
  { id: 11, authors: 'Jumper, E.J.', title: 'An Overview of the Testing Performed by the Shroud of Turin Research Project with a Summary of Results', publication: 'IEEE 1982 Proceedings of the International Conference on Cybernetics and Society, pp. 535-537', year: 1982, pdfUrl: 'https://www.shroud.com/pdfs/overview.pdf', category: 'REFEREED' },
  { id: 12, authors: 'Jumper, E.J., A.D. Adler, J.P. Jackson, S.F. Pellicori, J.H. Heller and J.R. Drusik', title: 'A Comprehensive Examination of the Various Stains and Images on the Shroud of Turin', publication: 'Archaeological Chemistry III, ACS Advances in Chemistry No. 205, Chapter 22, pp. 447-476', year: 1984, pdfUrl: 'https://www.shroud.com/pdfs/stains.pdf', category: 'REFEREED' },
  { id: 13, authors: 'Miller, V.D. and S.F. Pellicori', title: 'Ultraviolet Fluorescence Photography of the Shroud of Turin', publication: 'Journal of Biological Photography, Vol. 49, No. 3, pp. 71-85', year: 1981, pdfUrl: 'https://www.shroud.com/pdfs/uvfluor.pdf', category: 'REFEREED' },
  { id: 14, authors: 'Morris, R.A., L.A. Schwalbe and J.R. London', title: 'X-Ray Fluorescence Investigation of the Shroud of Turin', publication: 'X-Ray Spectrometry, Vol. 9, No. 2, pp. 40-47', year: 1980, pdfUrl: 'https://www.shroud.com/pdfs/xray.pdf', category: 'REFEREED' },
  { id: 15, authors: 'Mottern, R.W., R.J. London and R.A. Morris', title: 'Radiographic Examination of the Shroud of Turin - A Preliminary Report', publication: 'Materials Evaluation, Vol. 38, No. 12, pp. 39-44', year: 1980, pdfUrl: 'https://www.shroud.com/pdfs/radiograph.pdf', category: 'REFEREED' },
  { id: 16, authors: 'Pellicori, S.F.', title: 'Spectral Properties of the Shroud of Turin', publication: 'Applied Optics, Vol. 19, No. 12, pp. 1913-1920', year: 1980, pdfUrl: 'https://www.shroud.com/pdfs/pellicori.pdf', category: 'REFEREED' },
  { id: 17, authors: 'Pellicori, S. and M.S. Evans', title: 'The Shroud of Turin Through the Microscope', publication: 'Archaeology, January/February, pp. 34-43', year: 1981, pdfUrl: 'https://www.shroud.com/pdfs/microscope.pdf', category: 'REFEREED' },
  { id: 18, authors: 'Pellicori, S.F. and R.A. Chandos', title: 'Portable Unit Permits UV/vis Study of Shroud', publication: 'Industrial Research and Development, February, pp. 186-189', year: 1981, pdfUrl: 'https://www.shroud.com/pdfs/portable.pdf', category: 'REFEREED' },
  { id: 19, authors: 'Schwalbe, L.A. and R.N. Rogers', title: 'Physics and Chemistry of the Shroud of Turin, A Summary of the 1978 Investigation', publication: 'Analytica Chimica Acta, Vol. 135, pp. 3-49', year: 1982, pdfUrl: 'https://www.shroud.com/pdfs/schwalbe.pdf', category: 'REFEREED' },
  { id: 20, authors: 'Schwortz, B.M.', title: 'Mapping of Research Test-Point Areas on the Shroud of Turin', publication: 'IEEE 1982 Proceedings of the International Conference on Cybernetics and Society, pp. 538-547', year: 1982, pdfUrl: 'https://www.shroud.com/pdfs/schwortz.pdf', category: 'REFEREED' },
  { id: 21, authors: 'Bucklin, Robert', title: "The Shroud of Turin: A Pathologist's Viewpoint", publication: 'Legal Medicine Annual, pp. 33-39', year: 1982, pdfUrl: 'https://www.shroud.com/pdfs/bucklin.pdf', category: 'OTHER' },
  { id: 22, authors: 'Dinegar, Robert Hudson', title: 'The Shroud of Turin - A Look at the Overall Picture', publication: 'The Living Church, May 17, pp. 9-11', year: 1981, pdfUrl: 'https://www.shroud.com/pdfs/dinegar.pdf', category: 'OTHER' },
  { id: 23, authors: 'Jumper, E.J., K. Stevenson, Jr., and J.P. Jackson', title: 'Images of Coins on a Burial Cloth?', publication: 'The Numismatist, July, pp. 1349-1357', year: 1978, pdfUrl: 'https://www.shroud.com/pdfs/coins.pdf', category: 'OTHER' },
  { id: 24, authors: 'Miller, V., and D. Lynn', title: 'De Lijwade Van Turjin', publication: 'Natuur en Techniek, February, pp. 102-125', year: 1981, pdfUrl: 'https://www.shroud.com/pdfs/lijwade.pdf', category: 'OTHER' },
  { id: 25, authors: 'Jackson, J.P., E. Arthurs, L.A. Schwalbe, R.M. Sega, D.E. Windisch, W.H. Long, and E.A. Stappaerts', title: 'A New Tool for Cellulose Degradation Studies', publication: 'Materials Issues in Art and Archaeology: Symposium, Materials Research Society 123, pp. 311-316', year: 1988, pdfUrl: 'https://www.shroud.com/pdfs/cellulose1.pdf', category: 'FOLLOW_UP' },
  { id: 26, authors: 'Jackson, J.P., E. Arthurs, L.A. Schwalbe, R.M. Sega, D.E. Windisch, W.H. Long, and E.A. Stappaerts', title: 'Infrared Laser Heating for Studies of Cellulose Degradation', publication: 'Applied Optics 27(18), pp. 3937-3943', year: 1988, pdfUrl: 'https://www.shroud.com/pdfs/cellulose2.pdf', category: 'FOLLOW_UP' },
  { id: 27, authors: 'Dinegar, R.H. and L.A. Schwalbe', title: 'Isotope Measurements and Provenance Studies of the Turin Shroud', publication: 'Archaeological Chemistry IV, Advances in Chemistry Series 220, Chapter 23, pp. 409-417', year: 1989, abstractUrl: 'https://pubs.acs.org/doi/abs/10.1021/ba-1989-0220.ch023', category: 'FOLLOW_UP', notes: 'Abstract only - full paper available for purchase' },
  { id: 28, authors: 'Doyle, L.R., J.J. Lorre and E.B. Doyle', title: 'The application of computer image processing techniques to artifact analysis as applied to the Shroud of Turin study', publication: 'Studies in Conservation, Vol. 31, No. 1, pp. 1-6', year: 1986, abstractUrl: 'https://www.jstor.org/stable/1506246', category: 'FOLLOW_UP', notes: 'Abstract only' },
  { id: 29, authors: 'DeNiro, M.J., L. Sternberg, B. Marino and J. Drusik', title: 'Relation between D/H ratios and 18O and 16O ratios in cellulose from linen and maize', publication: 'Geochimica et Cosmochimica Acta, Vol. 52, pp. 2189-2196', year: 1988, pdfUrl: 'https://www.shroud.com/pdfs/deniro.pdf', category: 'FOLLOW_UP' },
  { id: 30, authors: 'Rogers, Raymond N.', title: 'Studies on the radiocarbon sample from the Shroud of Turin', publication: 'Thermochimica Acta, Vol. 425, Issues 1-2, pp. 189-194', year: 2005, pdfUrl: 'https://www.shroud.com/pdfs/rogers8.pdf', category: 'FOLLOW_UP', notes: 'Critical paper about C14 sample contamination' },
  { id: 31, authors: 'Devan, Donald, E. Jumper and J. Jackson', title: 'A Scientific Search for New Images on the Holy Shroud of Turin by Computer Enhancement', publication: 'Unpublished', year: 1974, pdfUrl: 'https://www.shroud.com/pdfs/devan1974.pdf', category: 'UNPUBLISHED' },
  { id: 32, authors: 'Mottern, Robert W. "Bill"', title: 'The Testing of a Relic', publication: 'ASNT Fall Conference Proceedings, pp. 279-282', year: 1979, pdfUrl: 'https://www.shroud.com/pdfs/mottern1979.pdf', category: 'UNPUBLISHED' },
  { id: 33, authors: 'Jumper, E.J., R.W. Mottern and J.P. Jackson', title: 'Nondestructive Testing of the Shroud of Turin: Project STURP', publication: 'Unpublished', year: 1979, pdfUrl: 'https://www.shroud.com/pdfs/ndt1979.pdf', category: 'UNPUBLISHED' },
  { id: 34, authors: 'Lynn, Donald J.', title: 'Some Anthropological Evidence Pertinent to the Shroud of Turin', publication: 'Unpublished', year: 1980, pdfUrl: 'https://www.shroud.com/pdfs/lynn1980.pdf', category: 'UNPUBLISHED' },
  { id: 35, authors: 'Riggi, Giovanni', title: 'The Dusts of the Holy Shroud of Turin - Progress Report', publication: 'STURP Meeting, New London, Connecticut', year: 1981, pdfUrl: 'https://www.shroud.com/pdfs/riggi1981.pdf', category: 'UNPUBLISHED', notes: 'Written before online translation - language may be awkward' },
  { id: 36, authors: 'Soran, Diane', title: 'Transcript of Remarks at Meeting of STURP Members', publication: 'Espanola, New Mexico', year: 1979, pdfUrl: 'https://www.shroud.com/pdfs/soran1979.pdf', category: 'UNPUBLISHED', notes: 'Professionally transcribed audio from Los Alamos lab meeting' },
  { id: 37, authors: 'Jumper, E.J. and J.P. Jackson (compilers)', title: 'Workshop Proceedings of the 1977 United States Conference on the Shroud of Turin', publication: 'Holy Shroud Guild', year: 1977, pdfUrl: 'https://www.shroud.com/pdfs/workshop1977.pdf', category: 'PROCEEDINGS', notes: '22 page summary of STURP planning' },
  { id: 38, authors: 'Stevenson, Kenneth (Editor)', title: 'Full Proceedings of the 1977 United States Conference on the Shroud of Turin', publication: 'Holy Shroud Guild', year: 1977, pdfUrl: 'https://www.shroud.com/pdfs/proceedings1977.pdf', category: 'PROCEEDINGS', notes: '132 page complete proceedings volume' },
  { id: 39, authors: 'Meacham, William (Archivist)', title: 'STURP II Testing Proposals 1984-88', publication: 'Archived Collection', year: 1988, abstractUrl: 'https://www.shroud.com/meacham2.htm', category: 'PROCEEDINGS', notes: 'Collection includes 1984, 1987, and 1988 testing proposals' },
  { id: 40, authors: 'Lukasik, S.J.', title: 'Some Speculations Concerning the Process Leading to the Formation of the Image on the Shroud of Turin', publication: 'Previously Unpublished', year: 1985, pdfUrl: 'https://www.shroud.com/pdfs/lukasik1985.pdf', category: 'UNPUBLISHED', notes: 'By the VP of Northrop Corp and former ARPA director' }
];